// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package ormu

type Task struct {
	ID       int64  `json:"id"`
	Mode     string `json:"mode"`
	Args     string `json:"args"`
	Config   string `json:"config"`
	Path     string `json:"path"`
	CreateAt int64  `json:"create_at"`
	StartAt  int64  `json:"start_at"`
	StopAt   int64  `json:"stop_at"`
	Info     string `json:"info"`
}
