// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package ormu

import (
	"context"
)

type Querier interface {
	AddTask(ctx context.Context, arg AddTaskParams) (*Task, error)
	GetTask(ctx context.Context, id int64) (*Task, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]*Task, error)
}

var _ Querier = (*Queries)(nil)
