// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: copyfrom.go

package orm

import (
	"context"
)

// iteratorForAddSymbols implements pgx.CopyFromSource.
type iteratorForAddSymbols struct {
	rows                 []AddSymbolsParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddSymbols) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddSymbols) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Exchange,
		r.rows[0].Market,
		r.rows[0].Symbol,
	}, nil
}

func (r iteratorForAddSymbols) Err() error {
	return nil
}

func (q *Queries) AddSymbols(ctx context.Context, arg []AddSymbolsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"exsymbol"}, []string{"exchange", "market", "symbol"}, &iteratorForAddSymbols{rows: arg})
}
