// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package ormo

import (
	"context"
)

type Querier interface {
	AddExOrder(ctx context.Context, arg AddExOrderParams) (int64, error)
	AddIOrder(ctx context.Context, arg AddIOrderParams) (int64, error)
	AddTask(ctx context.Context, arg AddTaskParams) (*BotTask, error)
	FindTask(ctx context.Context, arg FindTaskParams) (*BotTask, error)
	GetExOrders(ctx context.Context, inoutID int64) ([]*ExOrder, error)
	GetIOrder(ctx context.Context, id int64) (*IOrder, error)
	GetTask(ctx context.Context, id int64) (*BotTask, error)
	GetTaskPairs(ctx context.Context, arg GetTaskPairsParams) ([]string, error)
	ListTaskPairs(ctx context.Context, arg ListTaskPairsParams) ([]string, error)
	ListTasks(ctx context.Context) ([]*BotTask, error)
	SetExOrder(ctx context.Context, arg SetExOrderParams) error
	SetIOrder(ctx context.Context, arg SetIOrderParams) error
}

var _ Querier = (*Queries)(nil)
